enable_testing()

add_subdirectory(MultiThomas)
add_subdirectory(MultiThomasExample)
add_subdirectory(StaticArrays)
add_subdirectory(ImageFilter)
#add_subdirectory(TensorTranspose)
if (USE_EIGEN)
  add_subdirectory(MultiPrec)
endif()

add_test(NAME MultiThomasExample COMMAND MultiThomasExample)
add_test(NAME StaticArrays COMMAND StaticArrays)
if (USE_EIGEN)
  add_test(NAME MultiPrec COMMAND MultiPrec)
endif()
